version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
     - '90:4000'
    links:
      - mongo
addis:
  container_name: addis
  image: mongo
  port:
   - '27017:27017'

   